# docker-compose.yml
services:
  node-1:
    build: .
    container_name: node-1
    hostname: node-1
    ports: ["2222:22"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bash", "-lc", "nc -z localhost 22"]
      interval: 10s
      timeout: 3s
      retries: 10

  node-2:
    build: .
    container_name: node-2
    hostname: node-2
    ports: ["2223:22"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bash", "-lc", "nc -z localhost 22"]
      interval: 10s
      timeout: 3s
      retries: 10

  node-3:
    build: .
    container_name: node-3
    hostname: node-3
    ports: ["2224:22"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bash", "-lc", "nc -z localhost 22"]
      interval: 10s
      timeout: 3s
      retries: 10
