version: "3.8"

services:
  node-1:
    build: .
    container_name: node-1
    hostname: node-1
    privileged: true
    command: ["/sbin/init"]
    environment:
      - container=docker
    ports:
      - "2222:22"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    tty: true

  node-2:
    build: .
    container_name: node-2
    hostname: node-2
    privileged: true
    command: ["/sbin/init"]
    environment:
      - container=docker
    ports:
      - "2223:22"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    tty: true

  node-3:
    build: .
    container_name: node-3
    hostname: node-3
    privileged: true
    command: ["/sbin/init"]
    environment:
      - container=docker
    ports:
      - "2224:22"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    tty: true
